unit URContrato;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, RLReport, FMTBcd, DB, DBClient, Provider, SqlExpr;

type
  TfrmContrato = class(TForm)
    sqlTab: TSQLQuery;
    dspTab: TDataSetProvider;
    cdsTab: TClientDataSet;
    dsTab: TDataSource;
    cdsTabCOD_TRANS: TIntegerField;
    cdsTabDAT_CAD: TDateField;
    cdsTabTP_TRANS: TStringField;
    cdsTabCOD_COMP: TIntegerField;
    cdsTabCOD_VEND: TIntegerField;
    cdsTabVLR_TRANS: TSingleField;
    cdsTabDESCRICAO: TStringField;
    cdsTabMARCA: TStringField;
    cdsTabANO: TStringField;
    cdsTabHORA_REC: TTimeField;
    cdsTabKM: TStringField;
    cdsTabMODELO: TStringField;
    cdsTabCOR: TStringField;
    cdsTabPLACA: TStringField;
    cdsTabCHASSI: TStringField;
    cdsTabRENAVAN: TStringField;
    cdsTabCOMBUSTIVEL: TStringField;
    cdsTabF_PAG: TStringField;
    cdsTabBASE_CALCULO: TSingleField;
    cdsTabPERCENTUAL: TSingleField;
    cdsTabPRAZO: TIntegerField;
    cdsTabPARCELAS: TIntegerField;
    cdsTabENTRADA: TSingleField;
    cdsTabENTRADA_VEIC: TSingleField;
    cdsTabOBS: TBlobField;
    cdsTabPOSICAO: TStringField;
    cdsTabCOMPRADOR: TStringField;
    cdsTabVENDEDOR: TStringField;
    cdsTabOPERCAO: TStringField;
    cdsTabENDCOMP: TStringField;
    cdsTabCPFCOMP: TStringField;
    cdsTabRGCOMP: TStringField;
    cdsTabFONECOMP: TStringField;
    cdsTabENDVEND: TStringField;
    cdsTabCPFVEND: TStringField;
    cdsTabRGVEND: TStringField;
    cdsTabFONEVEND: TStringField;
    Parc: TSQLQuery;
    ParcVENCIMENTO: TDateField;
    ParcDESCRICAO: TStringField;
    ParcVLR_PARC: TSingleField;
    RLReport2: TRLReport;
    RLBand2: TRLBand;
    RLDraw10: TRLDraw;
    RLDraw11: TRLDraw;
    RLDraw12: TRLDraw;
    RLImage1: TRLImage;
    RLLabel39: TRLLabel;
    RLDraw13: TRLDraw;
    RLLabel40: TRLLabel;
    RLLabel41: TRLLabel;
    RLDraw14: TRLDraw;
    RLLabel42: TRLLabel;
    RLDraw15: TRLDraw;
    RLLabel43: TRLLabel;
    RLDraw16: TRLDraw;
    RLDBText28: TRLDBText;
    RLLabel44: TRLLabel;
    RLLabel45: TRLLabel;
    RLLabel46: TRLLabel;
    RLLabel47: TRLLabel;
    RLLabel48: TRLLabel;
    RLLabel49: TRLLabel;
    lblCompra1: TRLLabel;
    lblVEnda1: TRLLabel;
    lblTroca1: TRLLabel;
    RLDBText29: TRLDBText;
    RLLabel53: TRLLabel;
    RLDBText30: TRLDBText;
    RLDBText31: TRLDBText;
    RLDBText32: TRLDBText;
    RLDBText33: TRLDBText;
    RLDBText34: TRLDBText;
    RLDBText35: TRLDBText;
    RLDBText36: TRLDBText;
    RLDBText37: TRLDBText;
    RLDBText38: TRLDBText;
    RLDBText39: TRLDBText;
    RLDBText40: TRLDBText;
    RLDBText41: TRLDBText;
    RLLabel54: TRLLabel;
    RLLabel55: TRLLabel;
    RLLabel56: TRLLabel;
    RLLabel57: TRLLabel;
    RLLabel58: TRLLabel;
    RLLabel59: TRLLabel;
    RLLabel60: TRLLabel;
    RLLabel61: TRLLabel;
    RLLabel62: TRLLabel;
    RLLabel63: TRLLabel;
    RLLabel64: TRLLabel;
    RLLabel65: TRLLabel;
    RLLabel66: TRLLabel;
    RLLabel67: TRLLabel;
    RLDraw17: TRLDraw;
    RLDraw18: TRLDraw;
    RLLabel68: TRLLabel;
    RLDBText42: TRLDBText;
    RLDBText43: TRLDBText;
    RLLabel69: TRLLabel;
    RLLabel70: TRLLabel;
    RLLabel71: TRLLabel;
    RLLabel72: TRLLabel;
    RLLabel73: TRLLabel;
    RLLabel74: TRLLabel;
    RLLabel75: TRLLabel;
    RLLabel76: TRLLabel;
    RLLabel77: TRLLabel;
    RLLabel78: TRLLabel;
    RLLabel79: TRLLabel;
    RLDBText44: TRLDBText;
    RLDBText45: TRLDBText;
    RLDBText46: TRLDBText;
    RLDBText47: TRLDBText;
    RLDBText48: TRLDBText;
    RLDBText49: TRLDBText;
    RLDBText50: TRLDBText;
    RLDBText51: TRLDBText;
    RLDBText52: TRLDBText;
    RLDBText53: TRLDBText;
    RLDBText54: TRLDBText;
    RLDBMemo2: TRLDBMemo;
    RLLabel80: TRLLabel;
    RLMemo1: TRLMemo;
    RLDraw19: TRLDraw;
    RLLabel81: TRLLabel;
    RLDBText55: TRLDBText;
    RLDBText56: TRLDBText;
    RLDBText57: TRLDBText;
    RLDBText58: TRLDBText;
    RLLabel82: TRLLabel;
    RLDBText62: TRLDBText;
    RLDBText63: TRLDBText;
    RLDBText64: TRLDBText;
    cdsTabDESC_VEICCOMP: TStringField;
    cdsTabMARCA_COMP: TStringField;
    cdsTabANO_COMP: TStringField;
    cdsTabKM_COMP: TStringField;
    cdsTabMODELO_COMP: TStringField;
    cdsTabCOR_COMP: TStringField;
    cdsTabPLACA_COMP: TStringField;
    cdsTabCHASSI_COMP: TStringField;
    cdsTabRENAVAN_COMP: TStringField;
    cdsTabCOMBUSTIVEL_COMP: TStringField;
    RLDBText65: TRLDBText;
    RLLabel83: TRLLabel;
    RLDBText59: TRLDBText;
    RLDBText60: TRLDBText;
    RLReport1: TRLReport;
    RLBand1: TRLBand;
    RLDraw1: TRLDraw;
    RLDraw2: TRLDraw;
    RLDraw3: TRLDraw;
    RLLogo: TRLImage;
    RLLabel1: TRLLabel;
    RLDraw4: TRLDraw;
    RLLabel2: TRLLabel;
    RLLabel3: TRLLabel;
    RLDraw5: TRLDraw;
    RLLabel4: TRLLabel;
    RLDraw6: TRLDraw;
    RLLabel5: TRLLabel;
    RLDraw7: TRLDraw;
    RLDBText1: TRLDBText;
    RLLabel6: TRLLabel;
    RLLabel7: TRLLabel;
    RLLabel8: TRLLabel;
    RLLabel9: TRLLabel;
    RLLabel10: TRLLabel;
    RLLabel11: TRLLabel;
    lblCompra: TRLLabel;
    lblVenda: TRLLabel;
    lblTroca: TRLLabel;
    RLDBText2: TRLDBText;
    lblExtenso: TRLLabel;
    RLDBText3: TRLDBText;
    RLDBText4: TRLDBText;
    RLDBText5: TRLDBText;
    RLDBText6: TRLDBText;
    RLDBText7: TRLDBText;
    RLDBText8: TRLDBText;
    RLDBText9: TRLDBText;
    RLDBText10: TRLDBText;
    RLDBText11: TRLDBText;
    RLDBText12: TRLDBText;
    RLDBText13: TRLDBText;
    RLDBText14: TRLDBText;
    RLLabel16: TRLLabel;
    RLLabel17: TRLLabel;
    RLLabel18: TRLLabel;
    RLLabel19: TRLLabel;
    RLLabel20: TRLLabel;
    RLLabel21: TRLLabel;
    RLLabel22: TRLLabel;
    RLLabel23: TRLLabel;
    RLLabel24: TRLLabel;
    RLLabel25: TRLLabel;
    RLLabel26: TRLLabel;
    RLLabel27: TRLLabel;
    RLLabel28: TRLLabel;
    RLLabel29: TRLLabel;
    RLDraw8: TRLDraw;
    RLDraw9: TRLDraw;
    RLLabel30: TRLLabel;
    RLDBText15: TRLDBText;
    RLDBText16: TRLDBText;
    RLLabel31: TRLLabel;
    RLLabel32: TRLLabel;
    RLLabel33: TRLLabel;
    RLLabel34: TRLLabel;
    RLLabel35: TRLLabel;
    RLLabel36: TRLLabel;
    RLLabel37: TRLLabel;
    RLLabel38: TRLLabel;
    RLLabel50: TRLLabel;
    RLLabel51: TRLLabel;
    RLLabel52: TRLLabel;
    RLDBText17: TRLDBText;
    RLDBText18: TRLDBText;
    RLDBText19: TRLDBText;
    RLDBText20: TRLDBText;
    RLDBText21: TRLDBText;
    RLDBText22: TRLDBText;
    RLDBText23: TRLDBText;
    RLDBText24: TRLDBText;
    RLDBText25: TRLDBText;
    RLDBText26: TRLDBText;
    RLDBText27: TRLDBText;
    RLDBMemo1: TRLDBMemo;
    RLLabel84: TRLLabel;
    txtparcelas: TRLMemo;
    RLDraw20: TRLDraw;
    RLLabel85: TRLLabel;
    RLDBText61: TRLDBText;
    RLDBText66: TRLDBText;
    RLDBText67: TRLDBText;
    RLDBText68: TRLDBText;
    RLLabel86: TRLLabel;
    RLDBText69: TRLDBText;
    RLDBText70: TRLDBText;
    RLDBText71: TRLDBText;
    RLDBText72: TRLDBText;
    RLLabel87: TRLLabel;
    RLDBText73: TRLDBText;
    RLDBText74: TRLDBText;
    procedure RLBand1BeforePrint(Sender: TObject; var PrintIt: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmContrato: TfrmContrato;

implementation

uses UTransacao, UDados, ULTransacao, UFuncoes;

{$R *.dfm}

procedure TfrmContrato.RLBand1BeforePrint(Sender: TObject;
  var PrintIt: Boolean);
begin
   if trim(cdsTabOPERCAO.AsString) = 'Venda' then begin
      lblCompra.Visible := false; lblTroca.Visible := false; lblVenda.Visible := true;
      lblCompra1.Visible := false; lblTroca1.Visible := false; lblVenda1.Visible := true;
   end else if trim(cdsTabOPERCAO.AsString) = 'Troca' then begin
      lblCompra.Visible := false; lblTroca.Visible := true; lblVenda.Visible := false;
      lblCompra1.Visible := false; lblTroca1.Visible := true; lblVenda1.Visible := false;
   end else if trim(cdsTabOPERCAO.AsString) = 'Compra' then begin
      lblCompra.Visible := true; lblTroca.Visible := false; lblVenda.Visible := false;
      lblCompra1.Visible := true; lblTroca1.Visible := false; lblVenda1.Visible := false;
   end;

   lblExtenso.Caption := RemoveAcento(UpperCase(ValorPorExtenso(cdsTabVLR_TRANS.AsFloat)));
   RLLabel53.Caption := RemoveAcento(UpperCase(ValorPorExtenso(cdsTabVLR_TRANS.AsFloat)));
   Parc.Close;
   Parc.ParamByName('DATA_BASE').AsDate := cdsTabDAT_CAD.AsDateTime;
   Parc.ParamByName('COD_TRANS').AsInteger := cdsTabCOD_TRANS.AsInteger;
   Parc.Open;
   Parc.First;
   txtParcelas.Lines.Clear;
   while not Parc.Eof do begin
     txtParcelas.Lines.Add(ParcDESCRICAO.AsString + ' - ' +ParcVENCIMENTO.AsString + ' - ' + ParcVLR_PARC.DisplayText);
     RLMemo1.Lines.Add(ParcDESCRICAO.AsString + ' - ' +ParcVENCIMENTO.AsString + ' - ' + ParcVLR_PARC.DisplayText);
     Parc.Next;
   end;
  dados.cdsParam.Open;
   if not Dados.cdsParamLOGOTIPO.IsNull then begin
    ObtemFotoRel(dados.cdsParamLOGOTIPO, RLLogo);
    ObtemFotoRel(dados.cdsParamLOGOTIPO, RLImage1);
   end;
  dados.cdsParam.Close;
end;

end.
